/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <jni_md.h>
/* Header for class org_jni_InterfaceJNI */

#ifndef _Included_org_jni_InterfaceJNI
#define _Included_org_jni_InterfaceJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jni_InterfaceJNI
 * Method:    run_analysis
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jni_InterfaceJNI_run_1analysis
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
